version: "3.1"

services:

  mysql:

    image: mysql

    restart: always

    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=meeting-scheduler

    ports:
      - 33060:3306
