version: "3.1"

services:

  mysql:

    image: mysql

    restart: always

    environment:
      - MYSQL_ROOT_PASSWORD=password

    entrypoint:
      sh -c "
      echo 'CREATE DATABASE IF NOT EXISTS `meeting-scheduler`; CREATE DATABASE IF NOT EXISTS users;' > /docker-entrypoint-initdb.d/init.sql;
      /usr/local/bin/docker-entrypoint.sh --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
      "

    ports:
      - "33060:3306"

  zookeeper:

    image: docker.io/bitnami/zookeeper:3.7

    ports:
      - "2181:2181"

    restart: always

    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:

    image: docker.io/bitnami/kafka:2

    ports:
      - "9092:9092"

    restart: always

    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes

    depends_on:
      - zookeeper